### ISSUE TITLE
[ENVF Rev3] Diodes for reverse polarity power protection

### ISSUE THREAD

**Issue by pansapiens** [bummbummgarage/bummbummgarage.github.io#18]
If there is enough board space, some Schottky diodes (eg 1N5817 - 1N5819) for reverse polarity protection might be a good idea. While the keyed socket does the job, I've messed up polarity enough times somewhere to appreciate a second layer of protection (eg accidentally flipped home made power cables - a keyed socket won't save you !).

The advantages to this are:

- You can choose to use non-keyed power headers if you want and still have reverse polarity protection (eg if you only have simple 2x5 pin headers in stock)
- You can use 10 ohm resistors or "zero-ohm" wire jumpers instead if you don't have any Schottky diodes, or don't care about the extra protection.

The disadvantages I see are:

- Two more components, four more solder joints, more board space
- Added complexity if you choose to explain these as options in the build docs

**Comment by steffenlohaus** [comment]
Yes, will skip the reverse protection on this one. The space is just to little.
